### ISSUE TITLE
Failed to set argument `-f/--fracs` in `dxm_solveMethylation`

### ISSUE THREAD

**Issue by nshen7** [edwardslab-wustl/dxm#1] opened 2021-03-12 19:48 UTC
Hello @jfong1123 ,

I'm analyzing a bisulfite sequencing data with DXM, but I encountered an error while using the `-f/--fracs` argument in the function `dxm_solveMethylation`. Here is the test code with the example data incorporated in DXM package: 

> /home/nshen7/.local/bin/dxm_solveMethylation \
> -f 1 \
> -i /arc/project/st-kdkortha-1/nshen7/software/dxm/example_data/sampleInput.bed \
> -o data/test/testSample

 And following is the error output :
> usage: dxm_solveMethylation [-h] -i INFILE [-o OUTPREF] [-c MAXCOVERAGE]
>                             [-m MAXSUBPOP] [-f {0,1,2}]
>                             [-u USERSUPPLIEDFRACFILE] [-b BINFILE]
>                             [-q FREQFILE]
> dxm_solveMethylation: error: argument -f/--fracs: invalid choice: '1' (choose from 0, 1, 2)

Could you take a look into it?

Many thanks in advance!

Ning

**Comment by jredwards417** [comment] 2021-05-14 18:24
Apologies for not seeing this sooner!  This should be all fixed in the version I just uploaded. Please let me know if you run into other issues.

A few notes in case it is useful: 
- In general we have found using the default (-f 0) choices for the fractions works very well.  
- Using -f 1 will not work well for the test case in the example data, since it was designed to be a light weight test to be sure the installation worked. The code will run, but the answer may be unsatisfying.
- If you want to estimate the fractions directly from your data, we recommend estimating the cell fractions from a subset of regions that differ between the underlying cell types identified from an external data source rather than try to estimate them across the entire dataset.

**Closed as completed by jredwards417** 2021-05-14 18:24 UTC
